# -*- coding: utf-8 -*-
"""AprioriAlgorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KgX5Kse_r6GNE8Q8tuNWI_Hit98tG6yh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('/content/sepet.csv', header = None)
a, b = np.shape(data)

dataM = list()
for i in range(0, a):
  dataM.append([str(data.values[i, j]) for j in range(b)])

from apyori import apriori

kural = apriori(dataM, min_support = 0.01, min_confidence = 0.2, min_lift = 3, max_length = 2)

list(kural)

