# -*- coding: utf-8 -*-
"""randomSelection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-S3Q73_2VT0Pt28kOIGKhNhnGtHoUK9D
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

veriler = pd.read_csv('/content/Ads_CTR_Optimisation.csv')

import random
random.seed(0)

N = 10000   # how much random numbers you will create
d = 10    # there are ten ads
toplam = 0
secilenler = []

for n in range(0, N):
  add = random.randrange(d)
  secilenler.append(add)
  odul = veriler.values[n, add] # will choice a column for each row
  toplam = toplam + odul

toplam

plt.hist(secilenler)
plt.show

